/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BookRouteImport } from './routes/book'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ParlayRouteImport } from './routes/parlay'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PropsRouteImport } from './routes/props'
import { Route as RecordRouteImport } from './routes/record'
import { Route as SlateRouteImport } from './routes/slate'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ParlayRoute = ParlayRouteImport.update({
  id: '/parlay',
  path: '/parlay',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PropsRoute = PropsRouteImport.update({
  id: '/props',
  path: '/props',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const SlateRoute = SlateRouteImport.update({
  id: '/slate',
  path: '/slate',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/book': typeof BookRoute
  '/gates': typeof GatesRoute
  '/learn': typeof LearnRoute
  '/legal': typeof LegalRoute
  '/parlay': typeof ParlayRoute
  '/plans': typeof PlansRoute
  '/props': typeof PropsRoute
  '/record': typeof RecordRoute
  '/slate': typeof SlateRoute
  '/game/$gameId': typeof GameGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/book': typeof BookRoute
  '/gates': typeof GatesRoute
  '/learn': typeof LearnRoute
  '/legal': typeof LegalRoute
  '/parlay': typeof ParlayRoute
  '/plans': typeof PlansRoute
  '/props': typeof PropsRoute
  '/record': typeof RecordRoute
  '/slate': typeof SlateRoute
  '/game/$gameId': typeof GameGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/book': typeof BookRoute
  '/gates': typeof GatesRoute
  '/learn': typeof LearnRoute
  '/legal': typeof LegalRoute
  '/parlay': typeof ParlayRoute
  '/plans': typeof PlansRoute
  '/props': typeof PropsRoute
  '/record': typeof RecordRoute
  '/slate': typeof SlateRoute
  '/game/$gameId': typeof GameGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/book'
    | '/gates'
    | '/learn'
    | '/legal'
    | '/parlay'
    | '/plans'
    | '/props'
    | '/record'
    | '/slate'
    | '/game/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/book'
    | '/gates'
    | '/learn'
    | '/legal'
    | '/parlay'
    | '/plans'
    | '/props'
    | '/record'
    | '/slate'
    | '/game/$gameId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/book'
    | '/gates'
    | '/learn'
    | '/legal'
    | '/parlay'
    | '/plans'
    | '/props'
    | '/record'
    | '/slate'
    | '/game/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  BookRoute: typeof BookRoute
  GatesRoute: typeof GatesRoute
  LearnRoute: typeof LearnRoute
  LegalRoute: typeof LegalRoute
  ParlayRoute: typeof ParlayRoute
  PlansRoute: typeof PlansRoute
  PropsRoute: typeof PropsRoute
  RecordRoute: typeof RecordRoute
  SlateRoute: typeof SlateRoute
  GameGameIdRoute: typeof GameGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parlay': {
      id: '/parlay'
      path: '/parlay'
      fullPath: '/parlay'
      preLoaderRoute: typeof ParlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/props': {
      id: '/props'
      path: '/props'
      fullPath: '/props'
      preLoaderRoute: typeof PropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slate': {
      id: '/slate'
      path: '/slate'
      fullPath: '/slate'
      preLoaderRoute: typeof SlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  BookRoute: BookRoute,
  GatesRoute: GatesRoute,
  LearnRoute: LearnRoute,
  LegalRoute: LegalRoute,
  ParlayRoute: ParlayRoute,
  PlansRoute: PlansRoute,
  PropsRoute: PropsRoute,
  RecordRoute: RecordRoute,
  SlateRoute: SlateRoute,
  GameGameIdRoute: GameGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
