import type { WinnerPick } from "./types";

/**
 * WINNER PREDICTION RECORD — Track 2 of 2.
 *
 * One row per game on the slate: who the Monte Carlo engine projects to win
 * straight up, no spread, no total, no price. Generated by `card.unofficialWinners`
 * from the simulated win probability on the same paths that produce the betting
 * card — so it is a read off the algorithm, not a restatement of the favourite
 * or of the closing line.
 *
 * These are predictions, not bets. No line is attached and no EV is claimed,
 * which is exactly what separates this board from `ARCHIVE` in `history.ts`.
 * The desk grades it weekly so the engine carries a full-slate hit rate, Brier
 * score, log loss, and skill-vs-climate alongside the betting record — reported
 * independently of it.
 *
 * Deliberately empty for the same reason as the betting archive: the scoring
 * model was retuned and seeded Weeks 1–2 are not comparable. Live weeks append
 * here as each week's board is locked.
 */
export const WINNER_ARCHIVE: WinnerPick[] = [];

const LOCK_KEY = "syndicate.winners.v1";

export function loadLockedWinners(): WinnerPick[] {
  if (typeof localStorage === "undefined") return [];
  try {
    const raw = localStorage.getItem(LOCK_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as WinnerPick[];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function saveLockedWinners(rows: WinnerPick[]) {
  try {
    localStorage.setItem(LOCK_KEY, JSON.stringify(rows.slice(0, 200)));
  } catch {
    /* quota */
  }
}

/** Locked rows win over the static archive when ids collide. */
export function allWinners(extra: WinnerPick[] = []): WinnerPick[] {
  const locked = extra.length ? extra : loadLockedWinners();
  const seen = new Set(WINNER_ARCHIVE.map((t) => t.id));
  return [...WINNER_ARCHIVE, ...locked.filter((t) => !seen.has(t.id))];
}

export function winnerRecord(rows: WinnerPick[]) {
  const g = rows.filter((t) => t.result === "win" || t.result === "loss");
  const n = g.length;
  const hits = g.filter((t) => t.result === "win").length;
  const exp = n ? g.reduce((s, t) => s + t.pWin, 0) / n : 0;
  const brier = n
    ? g.reduce((s, t) => {
        const y = t.result === "win" ? 1 : 0;
        return s + (t.pWin - y) ** 2;
      }, 0) / n
    : 0;
  const logloss = n
    ? g.reduce((s, t) => {
        const y = t.result === "win" ? 1 : 0;
        const p = Math.min(1 - 1e-6, Math.max(1e-6, t.pWin));
        return s - (y * Math.log(p) + (1 - y) * Math.log(1 - p));
      }, 0) / n
    : 0;
  const brierBase = n
    ? g.reduce((s, t) => {
        const y = t.result === "win" ? 1 : 0;
        return s + (0.5 - y) ** 2;
      }, 0) / n
    : 0.25;
  const climate = n ? hits / n : 0.5;
  const brierClimate = n
    ? g.reduce((s, t) => {
        const y = t.result === "win" ? 1 : 0;
        return s + (climate - y) ** 2;
      }, 0) / n
    : 0;
  return {
    n,
    hits,
    losses: n - hits,
    hitRate: n ? hits / n : 0,
    exp,
    brier,
    logloss,
    brierBase,
    brierClimate,
    skill: brierClimate > 0 ? 1 - brier / brierClimate : 0,
    skillVsCoin: brierBase > 0 ? 1 - brier / brierBase : 0,
  };
}

export const CONF_BANDS = [
  { id: "toss", label: "Toss-up", lo: 0, hi: 0.55 },
  { id: "lean", label: "Lean", lo: 0.55, hi: 0.65 },
  { id: "strong", label: "Strong", lo: 0.65, hi: 1.01 },
] as const;

export function winnerBands(rows: WinnerPick[]) {
  const g = rows.filter((t) => t.result === "win" || t.result === "loss");
  return CONF_BANDS.map((b) => {
    const xs = g.filter((t) => t.pWin >= b.lo && t.pWin < b.hi);
    return { ...b, ...winnerRecord(xs) };
  });
}

export function winnerByWeek(rows: WinnerPick[]) {
  const weeks = [...new Set(rows.map((r) => r.week))].sort((a, b) => a - b);
  return weeks.map((week) => {
    const xs = rows.filter((r) => r.week === week);
    return { week, games: xs.length, ...winnerRecord(xs), rows: xs };
  });
}
